#undef self
#undef const_self
#undef require_method

#undef METHOD_INIT
#undef METHOD_DECLARE
#undef METHOD_DEF_BEGIN
#undef METHOD_DEF_END
#undef IMPL_METHOD_BEGIN
#undef IMPL_METHOD_BEGIN_WITH_REQUIRES
#undef IMPL_METHOD_FOR
#undef IMPL_METHOD_END

#undef FACTORY_DECLARE
#undef FACTORY_DEF_BEGIN
#undef FACTORY_DEF_END
#undef IMPL_FACTORY_BEGIN
#undef IMPL_FACTORY_BEGIN_WITH_REQUIRES
#undef IMPL_FACTORY_FOR
#undef IMPL_FACTORY_END
